### ISSUE TITLE
Regressions in firstrunwizard

### ISSUE THREAD

**Issue by szaimen** [nextcloud/firstrunwizard#1183]
Just tested on 29.0.0 RC5:
![image](https://github.com/nextcloud/firstrunwizard/assets/42591237/e7ebc610-f015-4133-b54e-51193003bb8a)

1. The heading should be center-aligned
2. the logo should be positioned on top of the circle and not on the slide itself
3. The `What's new?` button should link to the `Introducing Nexcloud Hub 8` slide and not to the `New in Nextcloud Hub 8` slide

**Comment by jancborchardt** [comment]
@sorbaugh @AndyScherzinger for regression on something that everyone is likely to see.

**Comment by susnux** [comment]
> The heading should be center-aligned
> The What's new? button should link to the Introducing Nexcloud Hub 8 slide and not to the New in Nextcloud Hub 8 slide

fixed in #1185 

>  the logo should be positioned on top of the circle and not on the slide itself

I can not reproduce this, neither on master nor stable29. Neither with chrome nor with firefox
![localhost_8082_index php_apps_files_files_62_dir=_](https://github.com/nextcloud/firstrunwizard/assets/1855448/3dd2549b-a254-4388-ac24-e2b1dd79258e)
![Screen Shot 2024-04-23 at 01 10 30](https://github.com/nextcloud/firstrunwizard/assets/1855448/9780a82f-d010-4f95-95ec-3a6cb17856c7)

**Comment by szaimen** [comment]
> I can not reproduce this, neither on master nor stable29. Neither with chrome nor with firefox

Weird. I also can no longer reproduce the problem on c.nc.c... Yesterday it was there though. Anyway, fixing the heading and the forwarding sounds good :)
