### ISSUE TITLE
New nicer image for first step of first run wizard

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/firstrunwizard#72]
The first screen of the first run wizard should show a nice big picture to make the first run experience more pretty. The best would be to reuse a picture from our flyer. I guess best is to create an additional step before the current steps. 
I will share the picture separately. 

@skjnldsv @juliushaertl Can one of you look into this?

@jancborchardt as discussed

@rullzer for 14

**Comment by jancborchardt** [comment]
Thought it was already implemented through https://github.com/nextcloud/firstrunwizard/pull/71

@juliushaertl the screenshot you posted at https://github.com/nextcloud/firstrunwizard/pull/71#issuecomment-407061320 is great – we should do it like that. :)

@karlitschek maybe I remember wrong: Could you confirm if it's ok to replace the 3 icons (self-hosted, open standards, community-focused) or should there be _another_ slide for those? If we keep them in another slide, I would say we should remove one of the other slides because otherwise it's way too much text no one will read.

**Comment by karlitschek** [comment]
Ahh sorry. I missed that it's already done because it's not in the beta1. But maybe only a timing problem :-)

**Comment by karlitschek** [comment]
Hmmm. I think the first slide should be clean and simple. Exactly as in the screenshot here. This is great. Very nice!!!
I don't have strong impressions if we 1. move the 3 icons to the second slide and add a new slide or 2. move the 3 icons to the second slide and kill one of the other slides instead or 3. kill the 3 icons completely. My main focus is that I want a clean and nice first slide ;-)
What do you think? @jancborchardt @juliushaertl

**Comment by juliushaertl** [comment]
> The icons about the core values of Nextcloud were actually the main requirement for the firstrunwizard rework. See #57 so I wonder why those are supposed to be dropped again. Also just using the image instead of the text/icons as a first slide doesn't provide any value to the user. 

It was not included in #71 because the question on how we should handle the core values pages was still open. So we merged it as a first step without it.

While I get that the first slide should look nice and the image is a good enhancement there, I still think we should have some content that actually provides some information and value to the user there. 

@karlitschek @jancborchardt How do you think about combining the image with the core values page in something like this:
![screenshot from 2018-07-30 16-16-06](https://user-images.githubusercontent.com/3404133/43402886-00c29ab0-9414-11e8-9ac6-6bf2c0be3821.png)

**Comment by jancborchardt** [comment]
Yep, totally agree with @karlitschek. Without logo and slogan it lacks focus.

**Comment by rullzer** [comment]
Fixed in https://github.com/nextcloud/firstrunwizard/pull/73
