### ISSUE TITLE
Decouple JS from server

### ISSUE THREAD

**Issue by rullzer** [nextcloud/firstrunwizard#77]
It would be good to also follow here the principle of decoupling the javascript from the server.

Best would probably be if we'd move this to a vue app as well. So we can cleanup ancient server js deps more easy.

**Comment by juliushaertl** [comment]
I did some research today, but I couldn't find any suitable lightbox/slideshow component that would fit our needs. I'll further look into plain javascript variants, since it might be even nicer to just have some plain javascript for this. There is not that many dynamic stuff happening here, so it should also be fine without a full vue stack.

**Comment by rullzer** [comment]
Done
